<a href="https://colab.research.google.com/github/ydchen17/PPI_Analysis_Project/blob/main/ID_conversion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
! wget http://www.ebi.ac.uk/Tools/webservices/psicquic/mint/webservices/current/search/query/species:human
! wget http://www.ebi.ac.uk/Tools/webservices/psicquic/mint/webservices/current/search/query/species:yeast
#! wget http://www.ebi.ac.uk/Tools/webservices/psicquic/mint/webservices/current/search/query/species:fruit%20fly
#! wget http://www.ebi.ac.uk/Tools/webservices/psicquic/mint/webservices/current/search/query/species:mouse

--2021-10-13 00:35:29--  http://www.ebi.ac.uk/Tools/webservices/psicquic/mint/webservices/current/search/query/species:human
Resolving www.ebi.ac.uk (www.ebi.ac.uk)... 193.62.193.80
Connecting to www.ebi.ac.uk (www.ebi.ac.uk)|193.62.193.80|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: ‘species:human’

species:human           [              <=>   ]  64.46M  91.2KB/s    in 12m 45s

2021-10-13 00:48:17 (86.3 KB/s) - ‘species:human’ saved [67592187]

--2021-10-13 00:48:17--  http://www.ebi.ac.uk/Tools/webservices/psicquic/mint/webservices/current/search/query/species:yeast
Resolving www.ebi.ac.uk (www.ebi.ac.uk)... 193.62.193.80
Connecting to www.ebi.ac.uk (www.ebi.ac.uk)|193.62.193.80|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: ‘species:yeast’

species:yeast           [       <=>          ]  38.44M  62.1KB/s    in 4m 15s

2021-10-13 00:52:35 (155 KB/s) - ‘species:yeast’ saved [40312554]

In [ ]:
# just use the function below.

In [ ]:
import urllib.parse
import urllib.request

# basic ID conversion function
def ID_conversion(gene_list, from_type, to_type):
  gene_list_tab = ""
  for i in gene_list:
    gene_list_tab += str(i)+" "  
  params = {
      'from': from_type,
      'to': to_type,
      'format': 'tab',
      'query': gene_list_tab
      }
  data = urllib.parse.urlencode(params)
  data = data.encode('utf-8')
  req = urllib.request.Request('https://www.uniprot.org/uploadlists/', data)
  with urllib.request.urlopen(req) as f:
        response = f.read()
  df = pd.DataFrame([x.split('\t') for x in response.decode('utf-8').split('\n')])
  df.columns = df.iloc[0]
  return df[1:][:-1]

In [ ]:
# ID_conversion(genelist, 'ID', "P_ENTREZGENEID")
# ID_conversion(genelist, 'ID', "ENSEMBLGENOME_ID")
# ID_conversion(["dsadas"], 'ID', "P_ENTREZGENEID") # will return no result

# ID_conversion(interactorA, 'ID', "P_ENTREZGENEID").to_csv("You location here")
# ID_conversion(interactorA, 'ID', "P_ENTREZGENEID")[["From"]].to_csv("You location here")
# ID_conversion(interactorA, 'ID', "P_ENTREZGENEID")[["To"]].to_csv("You location here")

In [ ]:
import pandas as pd
human_ppi_edges = pd.read_csv("/content/species:human", sep = "\t", header = None)[[0,1]]
yeast_ppi_edges = pd.read_csv("/content/species:yeast", sep = "\t", header = None)[[0,1]]
#mouse_ppi_edges = pd.read_csv("/content/species:mouse", sep = "\t", header = None)[[0,1]]
#fly_ppi_edges = pd.read_csv("/content/species:fruit fly", sep = "\t", header = None)[[0,1]]

In [ ]:
# Edge list to node list
def nodelist(edgelist):
  nodelist = list(set(edgelist[0].values.tolist()+(edgelist[1].values.tolist())))
  nodelist = pd.DataFrame(nodelist)[0].str.split(":", expand=True)
  nodelist = nodelist.replace("uniprotkb", "ACC+ID")
  nodelist = nodelist.replace("refseq", "P_REFSEQ_AC")
  nodelist = nodelist.replace("ensembl", "ENSEMBL_ID")
  nodelist = nodelist.replace("chebi", "CHEMBL_ID")
  return nodelist

# nodelist(yeast_ppi_edges)

In [ ]:
def node_ID_convert(nodelist, to_type):
  result_list =[]
  for group_label, group_data in nodelist.groupby(0):
    print(group_label)
    result_intrim = ID_conversion(list(group_data[1]), group_label, "ID").rename(columns={"From":"Original_ID", "To":"Interim_ID"})
    result_final = ID_conversion(result_intrim["Interim_ID"], "ID", to_type).rename(columns={"From":"Interim_ID", "To":"Target_ID"})
    result = result_intrim.join(result_final.set_index("Interim_ID"), on="Interim_ID")
    result_list.append(result)
    print(result)
  result_df = pd.concat(result_list)
  return result_df.reset_index(drop=True)

In [ ]:
yeast_ppi_converted = node_ID_convert(nodelist(yeast_ppi_edges), "P_ENTREZGENEID")

ACC+ID
0    Original_ID   Interim_ID Target_ID
1         Q04629   SWF1_YEAST    851704
2         Q04949   DYN3_YEAST    855345
3         P23287  PP2B1_YEAST    851153
4         P46367  ALDH4_YEAST    854556
5         P42844  ZIM17_YEAST    855406
...          ...          ...       ...
4989      P24088  YRF18_YEAST    851189
4989      P24088  YRF18_YEAST    852158
4989      P24088  YRF18_YEAST    854577
4990      P32469   DPH5_YEAST    850869
4991      Q12446  LAS17_YEAST    854353

[5178 rows x 3 columns]
P_REFSEQ_AC
0 Original_ID   Interim_ID Target_ID
1   NP_010706  RL12A_YEAST    852026
1   NP_010706  RL12A_YEAST    856656
2   NP_010706  RL12B_YEAST    852026
2   NP_010706  RL12B_YEAST    856656
intact
Empty DataFrame
Columns: [Original_ID, Interim_ID, Target_ID]
Index: []

In [ ]:
yeast_ppi_converted

0    Original_ID   Interim_ID Target_ID
0         Q02805   ROD1_YEAST    854183
1         Q12078   SMF3_YEAST    850721
2         P30775   RF1M_YEAST    852734
3         P17536   TPM1_YEAST    855645
4         P36024   SIS2_YEAST    853946
...          ...          ...       ...
5177      Q99219  YI31A_YEAST       NaN
5178   NP_010706  RL12A_YEAST    852026
5179   NP_010706  RL12A_YEAST    856656
5180   NP_010706  RL12B_YEAST    852026
5181   NP_010706  RL12B_YEAST    856656

[5182 rows x 3 columns]

In [ ]:
yeast_node_

In [ ]:
! pip install gprofiler-official
# get ortholog list
def get_orth(nodelist):
  from gprofiler import GProfiler
  gp = GProfiler(return_dataframe=True)
  orth = gp.orth(organism='scerevisiae',
            query=nodelist,
            target='hsapiens')
  return orth

Collecting gprofiler-official
  Downloading gprofiler_official-1.0.0-py3-none-any.whl (9.3 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from gprofiler-official) (2.23.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->gprofiler-official) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->gprofiler-official) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->gprofiler-official) (2021.5.30)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->gprofiler-official) (3.0.4)
Installing collected packages: gprofiler-official
Successfully installed gprofiler-official-1.0.0

In [ ]:
yeast_to_human = get_orth(nodelist(yeast_ppi_edges)[1].values.tolist())[["incoming","converted","ortholog_ensg","name"]]
yeast_to_human_converted = ID_conversion(yeast_to_human['ortholog_ensg'].values.tolist(), "ENSEMBL_ID", "SWISSPROT")
yeast_to_human_converted = yeast_to_human_converted.rename(columns={"To":"homolog_uniprot", "From":"ortholog_ensg"})
yeast_to_human = yeast_to_human.join(yeast_to_human_converted.set_index("ortholog_ensg"), on = "ortholog_ensg")

In [ ]:
yeast_to_human_converted

0       ortholog_ensg homolog_uniprot
1     ENSG00000006534          P43353
2     ENSG00000072210          P51648
3     ENSG00000108602          P30838
4     ENSG00000111275          P05091
5     ENSG00000118514          Q9H2A2
...               ...             ...
3293  ENSG00000127837          Q13685
3294  ENSG00000174145          Q9ULI1
3295  ENSG00000117543          Q9H2P9
3296  ENSG00000122574          A6NGB9
3297  ENSG00000171475          Q8TF74

[3297 rows x 2 columns]

In [ ]:
yeast_to_human.to_csv("/content/drive/MyDrive/Network_GroupProject/conservation_lists/evo_table.csv")

In [ ]:
yeast_to_human

     incoming converted    ortholog_ensg     name homolog_uniprot
0      Q04629   YDR126W              N/A      N/A             NaN
1      Q04949   YMR299C              N/A      N/A             NaN
2      P23287   YLR433C              N/A      N/A             NaN
3      P46367   YOR374W  ENSG00000006534  ALDH3B1          P43353
4      P46367   YOR374W  ENSG00000072210  ALDH3A2          P51648
...       ...       ...              ...      ...             ...
8246   P24088       nan              N/A      N/A             NaN
8247   P32469   YLR172C  ENSG00000117543     DPH5          Q9H2P9
8248   Q12446   YOR181W  ENSG00000115935    WIPF1          O43516
8249   Q12446   YOR181W  ENSG00000122574    WIPF3          A6NGB9
8250   Q12446   YOR181W  ENSG00000171475    WIPF2          Q8TF74

[8254 rows x 5 columns]

In [ ]:
yeast_conserved = set(yeast_to_human.dropna()["incoming"].values.tolist())

In [ ]:
len(yeast_conserved)

2164

In [ ]:
with open("/content/drive/MyDrive/Network_GroupProject/conservation_lists/yeast_conserved.txt", "w") as f:
  for i in yeast_conserved:
    f.write(i+"\n")

In [ ]:
yeast_all = set(nodelist(yeast_ppi_edges)[1].values.tolist())

In [ ]:
len(yeast_all)

4972

In [ ]:
with open("/content/drive/MyDrive/Network_GroupProject/conservation_lists/yeast_all.txt", "w") as f:
  for i in yeast_all:
    f.write(i+"\n")

In [ ]:
yeast_specific = [node for node in yeast_all if node not in yeast_conserved]

In [ ]:
len(yeast_specific)

2808

In [ ]:
with open("/content/drive/MyDrive/Network_GroupProject/conservation_lists/yeast_specific.txt", "w") as f:
  for i in yeast_specific:
    f.write(i+"\n")

In [ ]:
human_conserved_all = set(yeast_to_human["homolog_uniprot"].values.tolist())
len(human_conserved_all)

3291

In [ ]:
human_all = set(nodelist(human_ppi_edges)[1].values.tolist())
len(human_all)

13359

In [ ]:
with open("/content/drive/MyDrive/Network_GroupProject/conservation_lists/human_all.txt", "w") as f:
  for i in human_all:
    f.write(str(i)+"\n")

In [ ]:
human_conserved = [node for node in human_conserved_all if node in human_all]
len(human_conserved)

2214

In [ ]:
with open("/content/drive/MyDrive/Network_GroupProject/conservation_lists/human_conserved.txt", "w") as f:
  for i in human_conserved:
    f.write(str(i)+"\n")

In [ ]:
human_specific = [node for node in human_all if node not in human_conserved_all]
len(human_specific)

11145

In [ ]:
with open("/content/drive/MyDrive/Network_GroupProject/conservation_lists/human_specific.txt", "w") as f:
  for i in human_specific:
    f.write(str(i)+"\n")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
%%bash
cd /content/drive/MyDrive/Network_GroupProject/conservation_lists/
wget http://www.ebi.ac.uk/Tools/webservices/psicquic/mint/webservices/current/search/query/species:human 
wget http://www.ebi.ac.uk/Tools/webservices/psicquic/mint/webservices/current/search/query/species:yeast
wget http://www.ebi.ac.uk/Tools/webservices/psicquic/mint/webservices/current/search/query/species:fruit%20fly
wget http://www.ebi.ac.uk/Tools/webservices/psicquic/mint/webservices/current/search/query/species:mouse

--2021-10-13 01:12:50--  http://www.ebi.ac.uk/Tools/webservices/psicquic/mint/webservices/current/search/query/species:human
Resolving www.ebi.ac.uk (www.ebi.ac.uk)... 193.62.193.80
Connecting to www.ebi.ac.uk (www.ebi.ac.uk)|193.62.193.80|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: ‘species:human’

     0K .......... .......... .......... .......... ..........  198K
    50K .......... .......... .......... .......... ..........  517K
   100K .......... .......... .......... .......... ..........  569K
   150K .......... .......... .......... .......... .......... 35.1M
   200K .......... .......... .......... .......... .......... 2.63M
   250K .......... .......... .......... .......... ..........  682K
   300K .......... .......... .......... .......... .......... 2.73M
   350K .......... .......... .......... .......... .......... 21.9K
   400K .......... .......... .......... .......... ..........  273K
   450K .......... .......... .......... .......... ..........  543K
   500K .......... .......... .......... .......... .......... 19.0M
   550K .......... .......... .......... .......... .......... 34.4M
   600K .......... .......... .......... .......... ..........  569K
   650K .......... .......... .......... .......... .......... 30.8M
   700K .......... .......... .......... .......... .......... 75.0M
   750K .......... .......... .......... .......... .......... 58.1M
   800K .......... .......... .......... .......... .......... 26.9K
   850K .......... .......... .......... .......... ..........  272K
   900K .......... .......... .......... .......... ..........  551K
   950K .......... .......... .......... .......... .......... 32.5M
  1000K .......... .......... .......... .......... .......... 22.3M
  1050K .......... .......... .......... .......... ..........  560K
  1100K .......... .......... .......... .......... .......... 45.2M
  1150K .......... .......... .......... .......... .......... 56.6M
  1200K .......... .......... .......... .......... .......... 39.9M
  1250K .......... .......... .......... .......... .......... 24.2K
  1300K .......... .......... .......... .......... ..........  544K
  1350K .......... .......... .......... .......... ..........  543K
  1400K .......... .......... .......... .......... .......... 23.0M
  1450K .......... .......... .......... .......... ..........  562K
  1500K .......... .......... .......... .......... .......... 18.2M
  1550K .......... .......... .......... .......... .......... 25.0M
  1600K .......... .......... .......... .......... .......... 19.5M
  1650K .......... .......... .......... .......... .......... 38.1K
  1700K .......... .......... .......... .......... ..........  273K
  1750K .......... .......... .......... .......... ..........  549K
  1800K .......... .......... .......... .......... ..........  543K
  1850K .......... .......... .......... .......... ..........  549K
  1900K .......... .......... .......... .......... ..........  550K
  1950K .......... .......... .......... .......... .......... 63.9M
  2000K .......... .......... .......... .......... ..........  550K
  2050K .......... .......... .......... .......... .......... 1.92M
  2100K .......... .......... .......... .......... .......... 24.4K
  2150K .......... .......... .......... .......... ..........  276K
  2200K .......... .......... .......... .......... ..........  542K
  2250K .......... .......... .......... .......... ..........  547K
  2300K .......... .......... .......... .......... .......... 13.7M
  2350K .......... .......... .......... .......... ..........  554K
  2400K .......... .......... .......... .......... ..........  554K
  2450K .......... .......... .......... .......... ..........  553K
  2500K .......... .......... .......... .......... .......... 28.2M
  2550K .......... .......... .......... .......... .......... 34.8K
  2600K .......... .......... .......... .......... ..........  546K
  2650K .......... .......... .......... .......... ..........  274K
  2700K .......... .......... .......... .......... ..........  546K
  2750K .......... .......... .......... .......... ..........  540K
  2800K .......... .......... .......... .......... ..........  547K
  2850K .......... .......... .......... .......... ..........  546K
  2900K .......... .......... .......... .......... ..........  542K
  2950K .......... .......... .......... .......... ..........  553K
  3000K .......... .......... .......... .......... .......... 12.5K
  3050K .......... .......... .......... .......... ..........  541K
  3100K .......... .......... .......... .......... ..........  545K
  3150K .......... .......... .......... .......... ..........  543K
  3200K .......... .......... .......... .......... ..........  547K
  3250K .......... .......... .......... .......... ..........  547K
  3300K .......... .......... .......... .......... .......... 40.1M
  3350K .......... .......... .......... .......... ..........  550K
  3400K .......... .......... .......... .......... ..........  553K
  3450K .......... .......... .......... .......... .......... 35.6K
  3500K .......... .......... .......... .......... ..........  274K
  3550K .......... .......... .......... .......... ..........  547K
  3600K .......... .......... .......... .......... ..........  548K
  3650K .......... .......... .......... .......... ..........  545K
  3700K .......... .......... .......... .......... ..........  541K
  3750K .......... .......... .......... .......... ..........  551K
  3800K .......... .......... .......... .......... .......... 37.6M
  3850K .......... .......... .......... .......... ..........  546K
  3900K .......... .......... .......... .......... .......... 45.6K
  3950K .......... .......... .......... .......... ..........  273K
  4000K .......... .......... .......... .......... ..........  532K
  4050K .......... .......... .......... .......... ..........  543K
  4100K .......... .......... .......... .......... ..........  547K
  4150K .......... .......... .......... .......... .......... 25.0M
  4200K .......... .......... .......... .......... ..........  545K
  4250K .......... .......... .......... .......... ..........  555K
  4300K .......... .......... .......... .......... .......... 40.2K
  4350K .......... .......... .......... .......... ..........  274K
  4400K .......... .......... .......... .......... ..........  545K
  4450K .......... .......... .......... .......... ..........  547K
  4500K .......... .......... .......... .......... ..........  547K
  4550K .......... .......... .......... .......... ..........  541K
  4600K .......... .......... .......... .......... ..........  550K
  4650K .......... .......... .......... .......... ..........  551K
  4700K .......... .......... .......... .......... .......... 20.1M
  4750K .......... .......... .......... .......... .......... 29.1K
  4800K .......... .......... .......... .......... ..........  272K
  4850K .......... .......... .......... .......... ..........  546K
  4900K .......... .......... .......... .......... ..........  547K
  4950K .......... .......... .......... .......... ..........  537K
  5000K .......... .......... .......... .......... ..........  545K
  5050K .......... .......... .......... .......... ..........  551K
  5100K .......... .......... .......... .......... ..........  544K
  5150K .......... .......... .......... .......... ..........  554K
  5200K .......... .......... .......... .......... .......... 63.9M
  5250K .......... .......... .......... .......... .......... 25.8K
  5300K .......... .......... .......... .......... ..........  536K
  5350K .......... .......... .......... .......... ..........  539K
  5400K .......... .......... .......... .......... ..........  545K
  5450K .......... .......... .......... .......... ..........  554K
  5500K .......... .......... .......... .......... ..........  551K
  5550K .......... .......... .......... .......... .......... 5.41M
  5600K .......... .......... .......... .......... ..........  597K
  5650K .......... .......... .......... .......... .......... 5.97M
  5700K .......... .......... .......... .......... .......... 31.6K
  5750K .......... .......... .......... .......... ..........  545K
  5800K .......... .......... .......... .......... ..........  543K
  5850K .......... .......... .......... .......... ..........  464K
  5900K .......... .......... .......... .......... ..........  549K
  5950K .......... .......... .......... .......... ..........  666K
  6000K .......... .......... .......... .......... ..........  550K
  6050K .......... .......... .......... .......... ..........  548K
  6100K .......... .......... .......... .......... .......... 2.90M
  6150K .......... .......... .......... .......... .......... 26.6K
  6200K .......... .......... .......... .......... ..........  545K
  6250K .......... .......... .......... .......... ..........  547K
  6300K .......... .......... .......... .......... ..........  548K
  6350K .......... .......... .......... .......... ..........  548K
  6400K .......... .......... .......... .......... ..........  547K
  6450K .......... .......... .......... .......... ..........  550K
  6500K .......... .......... .......... .......... ..........  552K
  6550K .......... .......... .......... .......... .......... 25.6M
  6600K .......... .......... .......... .......... .......... 36.7K
  6650K .......... .......... .......... .......... ..........  273K
  6700K .......... .......... .......... .......... ..........  544K
  6750K .......... .......... .......... .......... ..........  545K
  6800K .......... .......... .......... .......... ..........  549K
  6850K .......... .......... .......... .......... .......... 2.15M
  6900K .......... .......... .......... .......... ..........  711K
  6950K .......... .......... .......... .......... ..........  550K
  7000K .......... .......... .......... .......... ..........  552K
  7050K .......... .......... .......... .......... .......... 23.8M
  7100K .......... .......... .......... .......... .......... 36.8K
  7150K .......... .......... .......... .......... ..........  279K
  7200K .......... .......... .......... .......... ..........  537K
  7250K .......... .......... .......... .......... ..........  553K
  7300K .......... .......... .......... .......... ..........  547K
  7350K .......... .......... .......... .......... ..........  550K
  7400K .......... .......... .......... .......... ..........  554K
  7450K .......... .......... .......... .......... .......... 33.2M
  7500K .......... .......... .......... .......... ..........  554K
  7550K .......... .......... .......... .......... .......... 63.1M
  7600K .......... .......... .......... .......... .......... 28.6K
  7650K .......... .......... .......... .......... ..........  273K
  7700K .......... .......... .......... .......... ..........  540K
  7750K .......... .......... .......... .......... ..........  554K
  7800K .......... .......... .......... .......... ..........  551K
  7850K .......... .......... .......... .......... .......... 12.2M
  7900K .......... .......... .......... .......... ..........  564K
  7950K .......... .......... .......... .......... ..........  556K
  8000K .......... .......... .......... .......... .......... 33.7M
  8050K .......... .......... .......... .......... ..........  555K
  8100K .......... .......... .......... .......... .......... 20.7K
  8150K .......... .......... .......... .......... ..........  274K
  8200K .......... .......... .......... .......... ..........  544K
  8250K .......... .......... .......... .......... ..........  546K
  8300K .......... .......... .......... .......... ..........  541K
  8350K .......... .......... .......... .......... ..........  560K
  8400K .......... .......... .......... .......... .......... 13.0M
  8450K .......... .......... .......... .......... ..........  555K
  8500K .......... .......... .......... .......... .......... 26.2M
  8550K .......... .......... .......... .......... ..........  560K
  8600K .......... .......... .......... .......... .......... 20.6K
  8650K .......... .......... .......... .......... ..........  544K
  8700K .......... .......... .......... .......... ..........  273K
  8750K .......... .......... .......... .......... ..........  546K
  8800K .......... .......... .......... .......... ..........  546K
  8850K .......... .......... .......... .......... ..........  543K
  8900K .......... .......... .......... .......... ..........  547K
  8950K .......... .......... .......... .......... ..........  554K
  9000K .......... .......... .......... .......... .......... 17.3M
  9050K .......... .......... .......... .......... ..........  554K
  9100K .......... .......... .......... .......... ..........  558K
  9150K .......... .......... .......... .......... .......... 24.4K
  9200K .......... .......... .......... .......... ..........  543K
  9250K .......... .......... .......... .......... ..........  276K
  9300K .......... .......... .......... .......... ..........  543K
  9350K .......... .......... .......... .......... ..........  548K
  9400K .......... .......... .......... .......... ..........  551K
  9450K .......... .......... .......... .......... .......... 36.6M
  9500K .......... .......... .......... .......... ..........  550K
  9550K .......... .......... .......... .......... ..........  548K
  9600K .......... .......... .......... .......... ..........  122M
  9650K .......... .......... .......... .......... ..........  548K
  9700K .......... .......... .......... .......... .......... 20.4K
  9750K .......... .......... .......... .......... ..........  545K
  9800K .......... .......... .......... .......... ..........  530K
  9850K .......... .......... .......... .......... ..........  567K
  9900K .......... .......... .......... .......... ..........  548K
  9950K .......... .......... .......... .......... ..........  549K
 10000K .......... .......... .......... .......... .......... 55.0M
 10050K .......... .......... .......... .......... ..........  550K
 10100K .......... .......... .......... .......... ..........  122M
 10150K .......... .......... .......... .......... ..........  551K
 10200K .......... .......... .......... .......... .......... 41.0M
 10250K .......... .......... .......... .......... ..........  558K
 10300K .......... .......... .......... .......... .......... 21.2K
 10350K .......... .......... .......... .......... ..........  545K
 10400K .......... .......... .......... .......... ..........  547K
 10450K .......... .......... .......... .......... ..........  274K
 10500K .......... .......... .......... .......... ..........  541K
 10550K .......... .......... .......... .......... ..........  554K
 10600K .......... .......... .......... .......... ..........  548K
 10650K .......... .......... .......... .......... .......... 35.8M
 10700K .......... .......... .......... .......... ..........  547K
 10750K .......... .......... .......... .......... ..........  554K
 10800K .......... .......... .......... .......... .......... 14.2M
 10850K .......... .......... .......... .......... .......... 23.2K
 10900K .......... .......... .......... .......... ..........  274K
 10950K .......... .......... .......... .......... ..........  544K
 11000K .......... .......... .......... .......... ..........  547K
 11050K .......... .......... .......... .......... ..........  544K
 11100K .......... .......... .......... .......... ..........  542K
 11150K .......... .......... .......... .......... ..........  543K
 11200K .......... .......... .......... .......... ..........  544K
 11250K .......... .......... .......... .......... ..........  555K
 11300K .......... .......... .......... .......... .......... 16.3M
 11350K .......... .......... .......... .......... ..........  554K
 11400K .......... .......... .......... .......... .......... 25.0K
 11450K .......... .......... .......... .......... ..........  535K
 11500K .......... .......... .......... .......... ..........  542K
 11550K .......... .......... .......... .......... ..........  551K
 11600K .......... .......... .......... .......... ..........  549K
 11650K .......... .......... .......... .......... .......... 27.3M
 11700K .......... .......... .......... .......... ..........  544K
 11750K .......... .......... .......... .......... ..........  557K
 11800K .......... .......... .......... .......... .......... 41.9M
 11850K .......... .......... .......... .......... ..........  544K
 11900K .......... .......... .......... .......... .......... 21.4K
 11950K .......... .......... .......... .......... ..........  542K
 12000K .......... .......... .......... .......... ..........  532K
 12050K .......... .......... .......... .......... ..........  548K
 12100K .......... .......... .......... .......... ..........  546K
 12150K .......... .......... .......... .......... ..........  550K
 12200K .......... .......... .......... .......... ..........  566K
 12250K .......... .......... .......... .......... .......... 13.8M
 12300K .......... .......... .......... .......... ..........  567K
 12350K .......... .......... .......... .......... .......... 11.1M
 12400K .......... .......... .......... .......... .......... 22.7K
 12450K .......... .......... .......... .......... ..........  135K
 12500K .......... .......... .......... .......... ..........  285K
 12550K .......... .......... .......... .......... .......... 29.2K
 12600K .......... .......... .......... .......... ..........  543K
 12650K .......... .......... .......... .......... ..........  275K
 12700K .......... .......... .......... .......... ..........  547K
 12750K .......... .......... .......... .......... ..........  550K
 12800K .......... .......... .......... .......... .......... 20.0M
 12850K .......... .......... .......... .......... ..........  540K
 12900K .......... .......... .......... .......... ..........  560K
 12950K .......... .......... .......... .......... .......... 26.0K
 13000K .......... .......... .......... .......... ..........  272K
 13050K .......... .......... .......... .......... ..........  548K
 13100K .......... .......... .......... .......... ..........  545K
 13150K .......... .......... .......... .......... ..........  497K
 13200K .......... .......... .......... .......... ..........  600K
 13250K .......... .......... .......... .......... ..........  544K
 13300K .......... .......... .......... .......... ..........  550K
 13350K .......... .......... .......... .......... ..........  561K
 13400K .......... .......... .......... .......... .......... 14.2M
 13450K .......... .......... .......... .......... ..........  556K
 13500K .......... .......... .......... .......... .......... 39.2M
 13550K .......... .......... .......... .......... .......... 25.3K
 13600K .......... .......... .......... .......... ..........  539K
 13650K .......... .......... .......... .......... ..........  276K
 13700K .......... .......... .......... .......... ..........  546K
 13750K .......... .......... .......... .......... .......... 4.54M
 13800K .......... .......... .......... .......... ..........  603K
 13850K .......... .......... .......... .......... ..........  554K
 13900K .......... .......... .......... .......... .......... 3.17M
 13950K .......... .......... .......... .......... ..........  653K
 14000K .......... .......... .......... .......... .......... 3.20M
 14050K .......... .......... .......... .......... ..........  645K
 14100K .......... .......... .......... .......... .......... 18.0K
 14150K .......... .......... .......... .......... ..........  536K

In [ ]:
human_nodelist = list(set(human_ppi_edges[0].values.tolist()+(human_ppi_edges[1].values.tolist())))
human_nodelist[:10]

['uniprotkb:P41212',
 'uniprotkb:Q9H9J4-2',
 'uniprotkb:Q62083',
 'uniprotkb:Q61881',
 'uniprotkb:Q96GY3',
 'uniprotkb:Q13616',
 'uniprotkb:Q8WVX3',
 'uniprotkb:P49768',
 'uniprotkb:Q6PEY2',
 'uniprotkb:Q96PD7']

In [ ]:
yeast_nodelist = list(set(yeast_ppi_edges[0].values.tolist()+(yeast_ppi_edges[1].values.tolist())))
yeast_nodelist[:10]

['uniprotkb:Q04629',
 'uniprotkb:Q04949',
 'uniprotkb:P23287',
 'uniprotkb:P46367',
 'uniprotkb:P42844',
 'uniprotkb:P39552',
 'uniprotkb:Q06497',
 'uniprotkb:Q06389',
 'uniprotkb:P32357',
 'uniprotkb:Q06631']

In [ ]:
human_ppi_edges = pd.read_csv("/content/species:human", sep = "\t", header = None)[[0,1]]
human_ppi_edges[0] = human_ppi_edges[0].str.split(":", expand=True)[1]
human_ppi_edges[1] = human_ppi_edges[1].str.split(":", expand=True)[1]
human_ppi_edges.to_csv("/content/drive/MyDrive/Network_GroupProject/conservation_lists/human_ppi_edges.csv", header=False, index=False)

In [ ]:
yeast_ppi_edges = pd.read_csv("/content/species:yeast", sep = "\t", header = None)[[0,1]]
yeast_ppi_edges[0] = yeast_ppi_edges[0].str.split(":", expand=True)[1]
yeast_ppi_edges[1] = yeast_ppi_edges[1].str.split(":", expand=True)[1]
yeast_ppi_edges.to_csv("/content/drive/MyDrive/Network_GroupProject/conservation_lists/yeast_ppi_edges.csv", header=False, index=False)

In [ ]:
library(plotly) 
p <- dotplot(human_specific_ego, showCategory=30) 
ggplotly(p)

In [ ]:
human_all_entrez = ID_conversion(human_all, 'ACC+ID', "P_ENTREZGENEID") 
human_conserved_entrez = ID_conversion(human_conserved, 'ACC+ID', "P_ENTREZGENEID") 
human_specific_entrez = ID_conversion(human_specific, 'ACC+ID', "P_ENTREZGENEID") 
yeast_all_entrez = ID_conversion(yeast_all, 'ACC+ID', "P_ENTREZGENEID") 
yeast_conserved_entrez = ID_conversion(yeast_conserved, 'ACC+ID', "P_ENTREZGENEID") 
yeast_specific_entrez = ID_conversion(yeast_specific, 'ACC+ID', "P_ENTREZGENEID")

In [ ]:
def save_list(ID_list, filename):
  with open(filename, "w") as f:
    for i in ID_list:
      f.write(i+"\n")

In [ ]:
save_list(human_all_entrez["To"], "/content/drive/MyDrive/Network_GroupProject/conservation_lists/entrez/human_all_entrez.txt")
save_list(human_conserved_entrez["To"], "/content/drive/MyDrive/Network_GroupProject/conservation_lists/entrez/human_conserved_entrez.txt")
save_list(human_specific_entrez["To"], "/content/drive/MyDrive/Network_GroupProject/conservation_lists/entrez/human_specific_entrez.txt")
save_list(yeast_all_entrez["To"], "/content/drive/MyDrive/Network_GroupProject/conservation_lists/entrez/yeast_all_entrez.txt")
save_list(yeast_conserved_entrez["To"], "/content/drive/MyDrive/Network_GroupProject/conservation_lists/entrez/yeast_conserved_entrez.txt")
save_list(yeast_specific_entrez["To"], "/content/drive/MyDrive/Network_GroupProject/conservation_lists/entrez/yeast_specific_entrez.txt")

In [ ]:
human_all_GENENAME = ID_conversion(human_all, 'ACC+ID', "GENENAME") 
human_conserved_GENENAME = ID_conversion(human_conserved, 'ACC+ID', "GENENAME") 
human_specific_GENENAME = ID_conversion(human_specific, 'ACC+ID', "GENENAME") 
yeast_all_GENENAME = ID_conversion(yeast_all, 'ACC+ID', "GENENAME") 
yeast_conserved_GENENAME = ID_conversion(yeast_conserved, 'ACC+ID', "GENENAME") 
yeast_specific_GENENAME = ID_conversion(yeast_specific, 'ACC+ID', "GENENAME")

In [ ]:
yeast_specific_GENENAME

0       From        To
1     Q12345      IES3
2     P49367      LYS4
3     P53933      APP1
4     P40342      SWM2
5     Q03855  TY1B-DR1
...      ...       ...
2869  Q12143      NSL1
2870  Q06508      LOA1
2871  P38723      COS8
2872  P53156   YGL081W
2873  P38623      RCK2

[2873 rows x 2 columns]

In [ ]:
save_list(human_all_GENENAME["To"], "/content/drive/MyDrive/Network_GroupProject/conservation_lists/gene_name/human_all_GENENAME.txt")
save_list(human_conserved_GENENAME["To"], "/content/drive/MyDrive/Network_GroupProject/conservation_lists/gene_name/human_conserved_GENENAME.txt")
save_list(human_specific_GENENAME["To"], "/content/drive/MyDrive/Network_GroupProject/conservation_lists/gene_name/human_specific_GENENAME.txt")
save_list(yeast_all_GENENAME["To"], "/content/drive/MyDrive/Network_GroupProject/conservation_lists/gene_name/yeast_all_GENENAME.txt")
save_list(yeast_conserved_GENENAME["To"], "/content/drive/MyDrive/Network_GroupProject/conservation_lists/gene_name/yeast_conserved_GENENAME.txt")
save_list(yeast_specific_GENENAME["To"], "/content/drive/MyDrive/Network_GroupProject/conservation_lists/gene_name/yeast_specific_GENENAME.txt")

In [ ]:
import pandas as pd
human_expression = pd.read_csv("/content/drive/MyDrive/Network_GroupProject/conservation_lists/expression_avg/human_expression.txt",skiprows=11, sep="\t")[["string_external_id","abundance"]]
human_expression

         string_external_id  abundance
0      9606.ENSP00000359240      1.190
1      9606.ENSP00000359596      0.556
2      9606.ENSP00000358965      0.002
3      9606.ENSP00000303057      8.250
4      9606.ENSP00000222157      0.203
...                     ...        ...
19944  9606.ENSP00000258821      1.470
19945  9606.ENSP00000355961      4.330
19946  9606.ENSP00000368190      3.500
19947  9606.ENSP00000360147      1.310
19948  9606.ENSP00000306157      0.122

[19949 rows x 2 columns]

In [ ]:
yeast_expression = pd.read_csv("/content/drive/MyDrive/Network_GroupProject/conservation_lists/expression_avg/yeast_expression.txt",skiprows=11, sep="\t")[["string_external_id","abundance"]]
yeast_expression

     string_external_id  abundance
0          4932.YLR201C      34.20
1          4932.YMR188C      49.90
2          4932.YLL002W      11.70
3          4932.YNL015W     127.00
4          4932.YHR022C       1.47
...                 ...        ...
6435       4932.YOR034C       7.65
6436       4932.YNL024C      13.80
6437       4932.YKL170W      37.20
6438       4932.YDL237W      40.70
6439       4932.YGR269W      15.30

[6440 rows x 2 columns]

In [ ]:
# yeast_expression["string_external_id"] = yeast_expression["string_external_id"].str.split(".", expand=True)[1]

In [ ]:
Interim_ID_table = ID_conversion(yeast_expression["string_external_id"].values.tolist(), "STRING_ID", "ID").rename(columns={"From":"string_external_id", "To":"Interim_ID"})
Final_ID_table = ID_conversion(Interim_ID_table["Interim_ID"].values.tolist(), "ID", "ACC").rename(columns={"From":"Interim_ID", "To":"UNIPROT"})
final_df = Interim_ID_table.set_index("Interim_ID").join(Final_ID_table.set_index("Interim_ID")).set_index("string_external_id").join(yeast_expression.set_index("string_external_id"))
final_df.to_csv("/content/drive/MyDrive/Network_GroupProject/conservation_lists/expression_avg/yeast_expression_converted.txt")

In [ ]:
Interim_ID_table = ID_conversion(human_expression["string_external_id"].values.tolist(), "STRING_ID", "ID").rename(columns={"From":"string_external_id", "To":"Interim_ID"})
Final_ID_table = ID_conversion(Interim_ID_table["Interim_ID"].values.tolist(), "ID", "ACC").rename(columns={"From":"Interim_ID", "To":"UNIPROT"})
final_df = Interim_ID_table.set_index("Interim_ID").join(Final_ID_table.set_index("Interim_ID")).set_index("string_external_id").join(human_expression.set_index("string_external_id"))
final_df.to_csv("/content/drive/MyDrive/Network_GroupProject/conservation_lists/expression_avg/human_expression_converted.txt")